---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-kubelet
  namespace: kube-system
  labels:
    app: fake-kubelet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fake-kubelet
  labels:
    app: fake-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - list
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-kubelet
  labels:
    app: fake-kubelet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fake-kubelet
subjects:
  - kind: ServiceAccount
    name: fake-kubelet
    namespace: kube-system
---
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
  labels:
    alpha.service-controller.kubernetes.io/exclude-balancer: "true"
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: fake
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    type: virtual-kubelet
  name: fake
spec:
  taints:
    - effect: NoSchedule
      key: virtual-kubelet.io/provider
      value: fake
---
apiVersion: v1
kind: Pod
metadata:
  name: fake-kubelet
  namespace: kube-system
  labels:
    app: fake-kubelet
spec:
  containers:
    - name: fake-kubelet
      image: wzshiming/fake-kubelet
      imagePullPolicy: IfNotPresent
      env:
        - name: NODE_NAME
          value: fake
        - name: HOST_IP
          value: 10.0.0.1
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  serviceAccount: fake-kubelet
  serviceAccountName: fake-kubelet
  restartPolicy: Always
---
